# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0003_auto_20170416_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ['-created_at']},
        ),
    ]
