# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0004_auto_20170416_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
