apiVersion: v1
kind: ReplicationController
metadata:
  name: passchecker
  labels:
    name: passchecker-app
spec:
  replicas: 2
  selector:
    name: passchecker-app
    type: prod
  template:
    metadata:
      labels:
        name: passchecker-app
        type: prod
    spec:
      containers:
        - name: barmaker-app
          image: passchecker_backend
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 80